//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Booking()
        {
            this.RoomBookeds = new HashSet<RoomBooked>();
        }
    
        public int BookingReferenceId { get; set; }
        public string SpecialRateCode { get; set; }
        public System.DateTime CheckIn { get; set; }
        public System.DateTime CheckOut { get; set; }
        public int NoOfRooms { get; set; }
        public double Tax { get; set; }
        public double ServiceCharge { get; set; }
        public Nullable<int> PointsEarned { get; set; }
        public string GuestId { get; set; }
        public long CreditCardNo { get; set; }
        public string CreditCardType { get; set; }
        public string CardExpiredDate { get; set; }
        public double TotalCost { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual SpecialRate SpecialRate { get; set; }
        public virtual ICollection<RoomBooked> RoomBookeds { get; set; }
    }
}
