//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.RoomBookeds = new HashSet<RoomBooked>();
        }
    
        public string RoomType { get; set; }
        public string RoomDesc { get; set; }
        public string BedType { get; set; }
        public double Rate { get; set; }
        public int Quantity { get; set; }
    
        public virtual ICollection<RoomBooked> RoomBookeds { get; set; }
    }
}
