//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class PastTransaction
    {
        public string Member_No { get; set; }
        public int Booking_Ref { get; set; }
        public string Check_In { get; set; }
        public string Check_Out { get; set; }
        public string Room { get; set; }
        public int No_of_Rooms { get; set; }
        public double Total_Cost { get; set; }
        public Nullable<int> Points { get; set; }
    }
}
