//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialRate
    {
        public SpecialRate()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public string Code { get; set; }
        public double SpecialRate1 { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
