//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ThreeHotelEntities : DbContext
    {
        public ThreeHotelEntities()
            : base("name=ThreeHotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Guest> Guests { get; set; }
        public DbSet<Room> Rooms { get; set; }
        public DbSet<SpecialRate> SpecialRates { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Occupancy> Occupancies { get; set; }
        public DbSet<PastTransaction> PastTransactions { get; set; }
        public DbSet<Booking> Bookings { get; set; }
        public DbSet<RoomBooked> RoomBookeds { get; set; }
    
        public virtual ObjectResult<SearchOccupancy_Result> SearchOccupancy(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchOccupancy_Result>("SearchOccupancy", startDateParameter, endDateParameter);
        }
    }
}
